# Generated by Django 4.2.6 on 2023-11-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('fono', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario', models.TextField()),
                ('cc_ami', models.BooleanField(default=False)),
            ],
        ),
    ]
