# Generated by Django 4.2.6 on 2023-11-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint2', '0002_mensajecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(help_text='Ingresa tu profesión', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'verbose_name': 'Mensajes de contacto', 'verbose_name_plural': 'Mensajes de contacto'},
        ),
        migrations.AddField(
            model_name='cuenta',
            name='Profesion',
            field=models.ManyToManyField(help_text='Ingresa tu profesión', to='sprint2.profesion'),
        ),
    ]
